### ISSUE TITLE
Is the checkpoint released?

### ISSUE THREAD

**Issue by lan41981** [LINs-lab/RDED#1]
I encountered a problem when I reproduced your outstanding work. The problem is that I can't find checkpints. Are the checkpoints of each dataset and each network released?
Thank you for this excellent work.

**Comment by sp12138** [comment]
@lan41981 Thanks for your interest and apologies for the inconvenience. The pre-trained models associated with the ImageNet dataset are readily available through torchvision. For other models, we adhere to the [SRe2L](https://github.com/VILA-Lab/SRe2L/tree/main/SRe2L) for training and acquisition. We intend to release all checkpoints at the earliest opportunity.

**Comment by lan41981** [comment]
> @lan41981 Thanks for your interest and apologies for the inconvenience. The pre-trained models associated with the ImageNet dataset are readily available through torchvision. For other models, we adhere to the [SRe2L](https://github.com/VILA-Lab/SRe2L/tree/main/SRe2L) for training and acquisition. We intend to release all checkpoints at the earliest opportunity.

Thanks a lot! Looking forward to your future work.
